// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    
    public static class Archetypes
    {

        public static readonly EntityArchetype[] Definitions =
		{
		};
    
        public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() 
        {
        };
    }     
    

}